// <auto-generated />
using System;
using LoginRazorBlog.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoginRazorBlog.Infrastructure.Migrations
{
    [DbContext(typeof(AuthContext))]
    [Migration("20220122233433_InitialCreate1")]
    partial class InitialCreate1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LoginRazorBlog.Domain.LocalAccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTimeUtc")
                        .HasColumnType("datetime");

                    b.Property<string>("LastLoginIp")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("LastLoginTimeUtc")
                        .HasColumnType("datetime");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.ToTable("LocalAccount", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ca421bc6-b9b8-408c-a7a7-1b7a62fcdaa1"),
                            CreateTimeUtc = new DateTime(2022, 1, 23, 6, 34, 32, 871, DateTimeKind.Local).AddTicks(2527),
                            PasswordHash = "+ObKUZdjjK7KFGia3w7kAEIOEtQbhy+SGGHhsMQQJfs=",
                            Username = "Admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
